language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

cache:
  directories:
    - stripe-mock

env:
  global:
    # N.B. Whenever this is updated, please update `tests/common.rs` as well
    - STRIPE_MOCK_VERSION=0.56.0

before_install:
  # Unpack and start stripe-mock so that the test suite can talk to it
  - |
    if [ ! -d "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}" ]; then
      mkdir -p stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
      curl -L "https://github.com/stripe/stripe-mock/releases/download/v${STRIPE_MOCK_VERSION}/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
    fi
  # - |
  #   stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/stripe-mock -strict-version-check > /dev/null &
  #   STRIPE_MOCK_PID=$!
  # - export PATH="${PATH}:${PWD}/stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}"

script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --verbose --all
  - cargo build --verbose --all --features async
  - cargo test --verbose --all
  - cargo test --verbose --features async --example async_create_charge