[package]
name = "stripe_misc"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"

[dependencies]
serde.workspace = true
smol_str.workspace = true
serde_json.workspace = true
stripe_types = {path = "../../stripe_types"}

http-types.workspace = true
async-stripe = {path = "../../async-stripe"}


stripe_shared = {path = "../../generated/stripe_shared"}


[features]
runtime-tokio-hyper = ["async-stripe/runtime-tokio-hyper"]
runtime-tokio-hyper-rustls = ["async-stripe/runtime-tokio-hyper-rustls"]
runtime-tokio-hyper-rustls-webpki = ["async-stripe/runtime-tokio-hyper-rustls-webpki"]
runtime-blocking = ["async-stripe/runtime-blocking"]
runtime-blocking-rustls = ["async-stripe/runtime-blocking-rustls"]
runtime-blocking-rustls-webpki = ["async-stripe/runtime-blocking-rustls-webpki"]
runtime-async-std-surf = ["async-stripe/runtime-async-std-surf"]

apple_pay_domain = []
climate_order = []
climate_product = []
climate_supplier = []
ephemeral_key = []
exchange_rate = []
financial_connections_account = []
financial_connections_session = []
financial_connections_transaction = []
identity_verification_report = []
identity_verification_session = []
reporting_report_run = []
reporting_report_type = []
scheduled_query_run = []
tax_calculation = []
tax_registration = []
tax_settings = []
tax_transaction = []
webhook_endpoint = []

full = ["apple_pay_domain",
"climate_order",
"climate_product",
"climate_supplier",
"ephemeral_key",
"exchange_rate",
"financial_connections_account",
"financial_connections_session",
"financial_connections_transaction",
"identity_verification_report",
"identity_verification_session",
"reporting_report_run",
"reporting_report_type",
"scheduled_query_run",
"tax_calculation",
"tax_registration",
"tax_settings",
"tax_transaction",
"webhook_endpoint"]


[package.metadata.docs.rs]
features = ["runtime-tokio-hyper", "full"]

