[package]
name = "async-stripe-connect"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"
name = "stripe_connect"

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
smol_str.workspace = true
miniserde.workspace = true
async-stripe-types = {path = "../../async-stripe-types", version = "1.0.0-alpha.4" }
async-stripe-client-core = {path = "../../async-stripe-client-core", version = "1.0.0-alpha.4" }

async-stripe-shared = {path = "../../generated/async-stripe-shared", version = "1.0.0-alpha.4" }


[features]
serialize = ["async-stripe-types/serialize","async-stripe-shared/serialize"]
deserialize = ["async-stripe-types/deserialize","async-stripe-shared/deserialize", "dep:serde_json"]
account = []
account_link = []
account_session = []
application_fee = []
application_fee_refund = []
apps_secret = []
capability = []
country_spec = []
external_account = []
login_link = []
person = []
topup = []
transfer = []
transfer_reversal = []

full = ["account",
"account_link",
"account_session",
"application_fee",
"application_fee_refund",
"apps_secret",
"capability",
"country_spec",
"external_account",
"login_link",
"person",
"topup",
"transfer",
"transfer_reversal"]


[package.metadata.docs.rs]
features = ["full"]

