[package]
name = "example-async-std"
version = "0.1.0"
authors = ["Alexander Lyon <arlyon@me.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.7.0", features = ["attributes"] }
stripe-rust = { version = "0.13", path = "../../", features = ["runtime-async-std-surf"] }
