[package]
name = "async-stripe-issuing"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"
name = "stripe_issuing"

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
smol_str.workspace = true
miniserde.workspace = true
tracing = { version = "0.1", default-features = false }
async-stripe-types = {path = "../../async-stripe-types", version = "1.0.0-rc.2" }
async-stripe-client-core = {path = "../../async-stripe-client-core", version = "1.0.0-rc.2" }

async-stripe-shared = {path = "../../generated/async-stripe-shared", version = "1.0.0-rc.2" }


[features]
serialize = ["async-stripe-types/serialize","async-stripe-shared/serialize"]
deserialize = ["async-stripe-types/deserialize","async-stripe-shared/deserialize", "dep:serde_json"]
issuing_authorization = []
issuing_card = []
issuing_cardholder = []
issuing_dispute = []
issuing_personalization_design = []
issuing_physical_bundle = []
issuing_token = []
issuing_transaction = []

full = ["issuing_authorization",
"issuing_card",
"issuing_cardholder",
"issuing_dispute",
"issuing_personalization_design",
"issuing_physical_bundle",
"issuing_token",
"issuing_transaction"]


[package.metadata.docs.rs]
features = ["full"]

