[package]
name = "async-stripe-billing"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"
name = "stripe_billing"

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
smol_str.workspace = true
miniserde.workspace = true
tracing = { version = "0.1", default-features = false }
async-stripe-types = {path = "../../async-stripe-types", version = "1.0.0-alpha.7" }
async-stripe-client-core = {path = "../../async-stripe-client-core", version = "1.0.0-alpha.7" }

async-stripe-shared = {path = "../../generated/async-stripe-shared", version = "1.0.0-alpha.7" }


[features]
serialize = ["async-stripe-types/serialize","async-stripe-shared/serialize"]
deserialize = ["async-stripe-types/deserialize","async-stripe-shared/deserialize", "dep:serde_json"]
billing_alert = []
billing_credit_balance_summary = []
billing_credit_balance_transaction = []
billing_credit_grant = []
billing_meter = []
billing_meter_event = []
billing_meter_event_adjustment = []
billing_meter_event_summary = []
billing_portal_configuration = []
billing_portal_session = []
credit_note = []
credit_note_line_item = []
invoice = []
invoice_item = []
invoice_line_item = []
invoice_payment = []
invoice_rendering_template = []
payment_record = []
plan = []
quote = []
subscription = []
subscription_item = []
subscription_schedule = []
tax_id = []
test_helpers_test_clock = []

full = ["billing_alert",
"billing_credit_balance_summary",
"billing_credit_balance_transaction",
"billing_credit_grant",
"billing_meter",
"billing_meter_event",
"billing_meter_event_adjustment",
"billing_meter_event_summary",
"billing_portal_configuration",
"billing_portal_session",
"credit_note",
"credit_note_line_item",
"invoice",
"invoice_item",
"invoice_line_item",
"invoice_payment",
"invoice_rendering_template",
"payment_record",
"plan",
"quote",
"subscription",
"subscription_item",
"subscription_schedule",
"tax_id",
"test_helpers_test_clock"]


[package.metadata.docs.rs]
features = ["full"]

