[package]
name = "async-stripe-fraud"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"
name = "stripe_fraud"

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
smol_str.workspace = true
miniserde.workspace = true
tracing = { version = "0.1", default-features = false }
async-stripe-types = {path = "../../async-stripe-types", version = "1.0.0-rc.0" }
async-stripe-client-core = {path = "../../async-stripe-client-core", version = "1.0.0-rc.0" }

async-stripe-shared = {path = "../../generated/async-stripe-shared", version = "1.0.0-rc.0" }


[features]
serialize = ["async-stripe-types/serialize","async-stripe-shared/serialize"]
deserialize = ["async-stripe-types/deserialize","async-stripe-shared/deserialize", "dep:serde_json"]
radar_early_fraud_warning = []
radar_value_list = []
radar_value_list_item = []
review = []

full = ["radar_early_fraud_warning",
"radar_value_list",
"radar_value_list_item",
"review"]


[package.metadata.docs.rs]
features = ["full"]

