name: OpenAPI
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
jobs:
  update-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - name: install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: regenerate openapi
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: openapi-install
      - name: verify
        id: verify
        # currently waiting for https://github.com/actions-rs/cargo/pull/206
        # so we use this in the mean time
        uses: arlyon/cargo@v1.0.4
        with:
          command: make
          args: verify --loglevel error
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: Generate latest changes from OpenApi spec
          title: Generate latest changes from OpenApi spec
          body: |
            This is an automated PR that tries to build the latest changes generated from the [Stripe OpenApi spec](https://github.com/stripe/openapi).

            Here are the missing exports:

            ```
            ${{ steps.verify.outputs.stdout }}
            ```
          branch: openapi
          branch-suffix: timestamp
          assignees: arlyon
